-- AlterTable
ALTER TABLE `users`
    ADD COLUMN `customerType` ENUM('INDIVIDUAL', 'LEGAL') NOT NULL DEFAULT 'INDIVIDUAL',
    ADD COLUMN `companyName` VARCHAR(191) NULL,
    ADD COLUMN `economicCode` VARCHAR(191) NULL,
    ADD COLUMN `approvalStatus` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'APPROVED',
    ADD COLUMN `notes` TEXT NULL;
